[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node_modules/.bin/prisma db push && node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
